# Generated by Django 3.0.3 on 2020-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='createdts',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='board',
            name='modifiedts',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일시'),
        ),
    ]
