# Generated by Django 3.0.3 on 2020-03-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200310_2343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='fc_boards',
        ),
    ]
