# Generated by Django 3.0.4 on 2020-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.CharField(max_length=300, verbose_name='내용')),
                ('createdts', models.DateField(auto_now_add=True, verbose_name='생성일시')),
                ('modifiedts', models.DateField(auto_now_add=True, verbose_name='수정일시')),
            ],
        ),
    ]
