# Generated by Django 3.0.4 on 2020-03-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='boards',
        ),
    ]
