# Generated by Django 3.0.3 on 2020-03-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email'),
        ('board', '0002_auto_20200303_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='createdts',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='modifiedts',
            field=models.DateTimeField(auto_now_add=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=120, verbose_name='제목'),
        ),
    ]
