# Generated by Django 3.0.3 on 2020-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200310_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default='NULL', verbose_name='내용'),
        ),
    ]
