# Generated by Django 3.0.3 on 2020-03-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '장고 사용자'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='django_user',
        ),
    ]
