# Generated by Django 3.0.3 on 2020-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200303_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='kee@jej.com', max_length=30, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
